default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :test do
    run_tests(
      scheme: "Vcarda",
      devices: ["iPhone 14"]
    )
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"],
      is_key_content_base64: true
    )

    build_app(
      scheme: "Vcarda",
      export_method: "app-store"
    )
    upload_to_testflight(api_key: api_key, changelog: ENV["RELEASE_NOTES"])
  end
end


