name: Android CI

on:
  push:
    paths:
      - 'android-app/**'
  pull_request:
    paths:
      - 'android-app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Make gradlew executable
        run: |
          if [ -f ./gradlew ]; then chmod +x ./gradlew; fi

      - name: Run unit tests, lint, and assembleDebug
        run: |
          ./gradlew test lint assembleDebug || (echo "Ensure Gradle wrapper is checked in under android-app/" && exit 1)

      - name: Upload debug APK
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android-app/app/build/outputs/apk/debug/*.apk


