name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Cache SPM
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            ~/Library/Caches/org.swift.swiftpm
            ~/Library/Developer/Xcode/SharedData/Previews/Simulator Devices
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
      - name: Install Bundler (optional)
        run: |
          if [ -f Gemfile ]; then
            gem install bundler && bundle install
          fi
      - name: Build
        run: |
          xcodebuild -scheme Vcarda -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14' build | xcpretty || exit 1
      - name: Test
        run: |
          xcodebuild -scheme Vcarda -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14' test | xcpretty || exit 1

  beta:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: build-test
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
      - name: Install Bundler
        run: |
          gem install bundler && bundle install
      - name: Extract release notes from CHANGELOG
        id: notes
        run: |
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          awk '/^## /{p++} p==1{print}' CHANGELOG.md >> $GITHUB_OUTPUT || true
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Fastlane beta (gated)
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_CONTENT: ${{ secrets.ASC_KEY_CONTENT }}
          RELEASE_NOTES: ${{ steps.notes.outputs.notes }}
        run: |
          bundle exec fastlane beta --env default


